apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: ingress
    type: internal
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
        - name: nginx-ingress-controller
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
     