apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Fury monitoring
  - ../vendor/katalog/monitoring/prometheus-operator
  - ../vendor/katalog/monitoring/prometheus-operated
  - ../vendor/katalog/monitoring/alertmanager-operated
  - ../vendor/katalog/monitoring/node-exporter
  - ../vendor/katalog/monitoring/kube-state-metrics
  - ../vendor/katalog/monitoring/grafana
  - ../vendor/katalog/monitoring/goldpinger
  - ../vendor/katalog/monitoring/configs

  # Fury logging
  - ../vendor/katalog/logging/elasticsearch-single
  - ../vendor/katalog/logging/fluentd
  - ../vendor/katalog/logging/kibana

  # # Fury Ingress
  - ../vendor/katalog/ingress/nginx
  - ../vendor/katalog/ingress/forecastle

  # Custom resources
  - resources/ingress.yaml

patchesStrategicMerge:
    - patches/monitoring/alertmanager-operated-replicas.yaml
    - patches/monitoring/alertmanager-operated-resources.yaml
    - patches/monitoring/prometheus-operated-resources.yaml
    - patches/monitoring/prometheus-operator-resources.yaml
    - patches/monitoring/grafana-resources.yaml
    - patches/ingress/nginx-ingress-controller-resources.yaml
    - patches/logging/fluentd-resources.yaml
    - patches/logging/kibana-resources.yaml
    - patches/logging/fluentbit-resources.yaml
    - patches/logging/elasticsearch-resources.yaml
