---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/appName: "Grafana"
    forecastle.stakater.com/icon: "https://github.com/stakater/ForecastleIcons/raw/master/grafana.png"
  namespace: monitoring
  name: grafana
spec:
  rules:
    - host: grafana.fury.info
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: http
