---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fluentd
  namespace: logging
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fluentd
          resources:
            requests:
              cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
spec:
  template:
    spec:
      containers:
        - name: fluent-bit
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
